services:
  # agent:
  #   build: model_agent
  #   restart: always
  #   volumes:
  #     - ~/.aws/:/root/.aws/:ro
  #   environment:
  #     - AWS_PROFILE=default
  #   networks:
  #     - agent_backend_net
  db:
    image: mariadb
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ['CMD-SHELL','mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 10s
      retries: 3
      start_period: 30s
    secrets:
      - db-password
    expose:
      - 3306
    ports:
      - '3306:3306'
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=user_db
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    networks:
      - was_backend_net
    volumes:
      - db_vol:/var/lib/mysql
      - ~/.aws/:/root/.aws/:ro
  backend:
    build:
      context: backend
      target: builder
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    restart: always
    networks:
      - web_frontend_net
      - was_backend_net
    volumes:
      - ~/.aws/:/root/.aws/:ro
    secrets:
      - db-password
    depends_on:
      db:
        condition: service_healthy
  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    networks:
      - web_frontend_net
    volumes:
      - ~/.aws/:/root/.aws/:ro
    depends_on:
      - backend
volumes:
  db_vol:
networks:
  web_frontend_net:
  was_backend_net:
  # agent_backend_net:
secrets:
  db-password:
    file: db/password.txt
